### ISSUE TITLE
Pipeline fails to run with sample data

### ISSUE THREAD

**Issue by ric-costa** [greninger-lab/revica#3] opened 2023-03-30 17:40 UTC
When running the pipeline with docker on WSL2 using the sample data provided in this repository using the following command 
`nextflow run greninger-lab/revica -r main -latest --reads example --outdir output -with-docker greningerlab/revica:ubuntu-20.04`
it fails on the Serotyping process. The error message is the following: 
`Error executing process > 'Serotyping (1)'

Caused by:
  Process `Serotyping (1)` terminated with an error exit status (1)

Command executed:

  #!/bin/bash

  blastn -out example_KF923898.1_HCOV_blast_output.txt -query example_KF923898.1_HCOV.consensus_final.fa -db VP1_164_annotated_nospaces.fasta -outfmt 6 -task blastn -max_target_seqs 1 -evalue 1e-5
  # outfmt6 default values: 'qaccver saccver pident length mismatch gapopen qstart qend sstart send'

  serotype=$(awk 'FNR==1{print val,$2}' example_KF923898.1_HCOV_blast_output.txt | cut -d "_" -f2- | cut -d "/" -f2-)
  echo $serotype > example_KF923898.1_HCOV_serotype.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  USAGE
    blastn [-h] [-help] [-import_search_strategy filename]
      [-export_search_strategy filename] [-task task_name] [-db database_name]
      [-dbsize num_letters] [-gilist filename] [-seqidlist filename]
      [-negative_gilist filename] [-negative_seqidlist filename]
      [-taxids taxids] [-negative_taxids taxids] [-taxidlist filename]
      [-negative_taxidlist filename] [-entrez_query entrez_query]
      [-db_soft_mask filtering_algorithm] [-db_hard_mask filtering_algorithm]
      [-subject subject_input_file] [-subject_loc range] [-query input_file]
      [-out output_file] [-evalue evalue] [-word_size int_value]
      [-gapopen open_penalty] [-gapextend extend_penalty]
      [-perc_identity float_value] [-qcov_hsp_perc float_value]
      [-max_hsps int_value] [-xdrop_ungap float_value] [-xdrop_gap float_value]
      [-xdrop_gap_final float_value] [-searchsp int_value]
      [-sum_stats bool_value] [-penalty penalty] [-reward reward] [-no_greedy]
      [-min_raw_gapped_score int_value] [-template_type type]
      [-template_length int_value] [-dust DUST_options]
      [-filtering_db filtering_database]
      [-window_masker_taxid window_masker_taxid]
      [-window_masker_db window_masker_db] [-soft_masking soft_masking]
      [-ungapped] [-culling_limit int_value] [-best_hit_overhang float_value]
      [-best_hit_score_edge float_value] [-subject_besthit]
      [-window_size int_value] [-off_diagonal_range int_value]
      [-use_index boolean] [-index_name string] [-lcase_masking]
      [-query_loc range] [-strand strand] [-parse_deflines] [-outfmt format]
      [-show_gis] [-num_descriptions int_value] [-num_alignments int_value]
      [-line_length line_length] [-html] [-sorthits sort_hits]
      [-sorthsps sort_hsps] [-max_target_seqs num_sequences]
      [-num_threads int_value] [-remote] [-version]

  DESCRIPTION
     Nucleotide-Nucleotide BLAST 2.11.0+

  Use '-help' to print detailed descriptions of command line arguments
  ========================================================================

  Error: Too many positional arguments (1), the offending value: /bin/bash
  Error:  (CArgException::eSynopsis) Too many positional arguments (1), the offending value: /bin/bash`
  
  I'm using the latest versions of WSL2, docker, nextflow and updated ubuntu.

**Comment by asereewit** [comment] 2023-04-11 22:43
Thanks for pointing out the issue! It was an issue with the blast docker image. I updated it and the problem is fixed now.

**Closed by asereewit** 2023-04-11 22:43 UTC

**Comment by ric-costa** [comment] 2023-04-13 15:30
Can confirm it's working great now, thank you for the quick resolution!
